name: Build boot2docker ISO

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Docker Version"
        required: true
        default: "20.10.9"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Prepare Environment
        run: docker system prune --all --force --volumes
      - name: Happy Eyeballs
        run: wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash

      - name: Check Kernel Config
        run: |
          kernDups="$(files/kernel-config.d/.check-dups.sh)"
          if [ -n "$kernDups" ]; then
            echo >&2 "KERNEL CONFIG DUPLICATES!"
            echo >&2 "$kernDups"
            exit 1
          fi

      - name: Build ISO
        run: |
          set -Eeuo pipefail -x
          docker build -t boot2docker/boot2docker .
          docker run --rm boot2docker/boot2docker > boot2docker.iso
        env:
          DOCKER_VERSION: ${{ github.event.inputs.version }}

      - name: Upload ISO
        uses: actions/upload-artifact@v2
        with:
          name: boot2docker.iso
          path: boot2docker.iso
